### ISSUE TITLE
Update to discord.js ver 14?

### ISSUE THREAD

**Issue by GillHoang** [issadarkthing/discordjs-rpg#1]
Can you update this to ver 14 pls, i really need this :>

**Comment by issadarkthing** [comment]
discord.js version 14 isn't out yet

**Comment by hocsinhgioitoan** [comment]
> discord.js version 14 isn't out yet

:( hope you will add more update, have a nice day

**Comment by hocsinhgioitoan** [comment]
> discord.js version 14 isn't out yet

idk, but can i have your discord name? i have some thing want to talk with you

**Comment by issadarkthing** [comment]
yeah, sure issadarkthing#4495

**Comment by hocsinhgioitoan** [comment]
> issadarkthing#4495

my name is YL ●  Normal bị ban owo#3106
